### ISSUE TITLE
input_shape values in training

### ISSUE THREAD

**Issue by leoncav** [198808xc/Pangu-Weather#17]
Hello, 
I was wondering if you could further clarify what steps are needed to compute the value of input_shape in the EarthAttention3D class, and/or provide the value of this variable with the training setting of your paper (ERA5 at 0.25 x 0.25 resolution)?
Thank you

**Comment by longtsing** [comment]
In the paper ，the author talk about the datasets are ERA5 that use the surface dataset and the upper dataset.

**Comment by leoncav** [comment]
> In the paper ，the author talk about the datasets are ERA5 that use the surface dataset and the upper dataset.

Thank you @longtsing. I am aware about ERA5 and input data.
My question refers to the variable "input_shape" used in the training pseudocode in the Earth specific layers and which is undefined in the code.
