### ISSUE TITLE
How to use 1-hour, 3-hour, 6-hour and 24-hour forecasts properly

### ISSUE THREAD

**Issue by bmkor** [198808xc/Pangu-Weather#18]
First of all, many thanks for open sourcing this incredible work. 

As far as I understand, the `pangu_weather_1.onnx` is for 1-hour forecast or in general `pangu_weather_h.onnx` for h-hour forecast for h $\in$ [1,3,6,24].  

As such, my question is supposing I got the 00z analysis data and I would like to have 09z forecast. What combinations should I consider? For example, should I use `pangu_weather_6.onnx` for obtaining 06z forecast, then applying `pangu_weather_3.onnx` to the forecast output to get 09z forecast or vice versa (i.e. 3 + 6) or I should use `pangu_weather_3.onnx` three times (3 + 3 + 3 = 9)? I assume that applying less would be better (so autoregressive error would accumulate less?). 

Many thanks in advance.

**Comment by 0rhisia0** [comment]
As per the paper you greedily apply the largest possible lead time model that doesn't exceed the forecast you want to generate (apply the fewest possible models as you said). So a 32 hour forecast would be (24 + 6 + 1 + 1).
