### ISSUE TITLE
关于EarthSpecificBlock Reshape的问题

### ISSUE THREAD

**Issue by morestart** [198808xc/Pangu-Weather#29]
在伪代码 
https://github.com/198808xc/Pangu-Weather/blob/f8dda09705c57e6ca5484e35cd1210ece0d737a0/pseudocode.py#L424
中将x reshape为了(B, 4, 2, 60, 6, 15, 12, 192),但是输入数据从论文中得知是Bx8x360x181x192，但是15x12=180,并不是原始数据181，请问这里应该如何理解？

**Comment by shwgao** [comment]
请问这里是怎么解决的？
