### ISSUE TITLE
pseudocode does not match paper

### ISSUE THREAD

**Issue by jacklishufan** [198808xc/Pangu-Weather#30]
Hi it seems these section of code does not match the architecture diagram
https://github.com/198808xc/Pangu-Weather/blob/main/pseudocode.py#L236
In particular, in [Fig2](https://arxiv.org/pdf/2211.02556.pdf) of the paper, there is a skip residual connection from the output of layer 1 to the input of layer 4. However, the code merely concatenates the output of layer 1 with layer 4. Can you elaborate on which one is correct?

On a separate note: do you have ablation results on the effectiveness of Earth-Specific Positional Bias vs vanilla ones used in Swin Transformer? I find this design particularly interesting, however, there seem to be no numerical results in the paper on this aspect.

**Comment by 198808xc** [comment]
1. The code exactly reflects what we have used in all experiments. We did draw a connection from Layer 1 to Layer 4 in the paper, and the connection means concatenation, not summation.

2. As we wrote in the paper, the ESP design accelerated the training procedure, i.e. it causes the loss to drop faster than the vanilla design of Swin -- this aligns with our motivation that the ESP helps to formulate useful information from the absolute coordinates. However, the ablative experiments are not complete (there is a limited insufficient budget) so we did not report full results in the paper.

**Comment by jacklishufan** [comment]
Hi Thanks for the reponse. Just to clarify, the correct pipeline, as reflected in the code is that the output of layer 4  is concatenated with the output of layer 1, according to this modified diagram. 
![image](https://github.com/198808xc/Pangu-Weather/assets/17161214/dd391e84-5982-4753-b90b-c77f0dab693b)
Is my understanding correct? 

My confusion was not on summation versus concatenation, but whether such operation happens before or after the layer 4. In the original diagram it seems there is something goint "into layer 4 from layer 1", however in the code only output of layer3 is passed to layer 4. This was the source of confusion.

```
    x = self.layer1(x, 8, 360, 181) 
    skip = x
    x = self.downsample(x, 8, 360, 181)
    x = self.layer2(x, 8, 180, 91) 
    x = self.layer3(x, 8, 180, 91) 
    x = self.upsample(x)
    x = self.layer4(x, 8, 360, 181) 
    x = Concatenate(skip, x)
```

**Comment by 198808xc** [comment]
Yes, you are right. The figure is a bit confusing, but the code is correct. To be clear, the output of Layer 1 and Layer 4 are concatenated for further computation.
