### ISSUE TITLE
第548行伪代码的疑问

### ISSUE THREAD

**Issue by JesperY** [198808xc/Pangu-Weather#36]
我在读伪代码的过程中对第548行的代码不太理解，以下是关于这行代码的详细信息：
第548行代码为`EarthSpecificBias = reshape(EarthSpecificBias, target_shape = [1]+EarthSpecificBias.shape)`
这行代码来自`class EarthAttention3D`的`forward(self, x, mask)`方法，相关代码块共有三行，如下：
`EarthSpecificBias = reshape(EarthSpecificBias, target_shape=(self.window_size[0]*self.window_size[1]*self.window_size[2], self.window_size[0]*self.window_size[1]*self.window_size[2], self.type_of_windows, self.head_number))`
`EarthSpecificBias = TransposeDimensions(EarthSpecificBias, (2, 3, 0, 1))`
`EarthSpecificBias = reshape(EarthSpecificBias, target_shape = [1]+EarthSpecificBias.shape)`
我知道这一段是为了将 EarthSpecificBias 转为和 attention 相同的形状，但我无法理解`[1]+EarthSpecificBias.shape`中`[1]`的含义，希望能得到一些指点。
感谢百忙之中的回答，这将会对我有很大的帮助！

**Comment by 198808xc** [comment]
这个[1]就是batch size，我们默认设置为1，显存够大的话可以改成其他数。
