### ISSUE TITLE
skip connection question

### ISSUE THREAD

**Issue by lizhuoq** [198808xc/Pangu-Weather#49]
I noticed in your arXiv paper that it mentions concatenating the output of the second layer of the encoder with the output of the seventh layer of the decoder in the channel dimension. However, in your pseudocode, you concatenate the output of the second layer of the encoder with the output of the eighth layer (i.e., the last layer of the decoder block). This seems inconsistent with the text. If I follow the approach described in the text, it appears that the eighth layer of the decoder has no effect. Could you please clarify which approach I should follow in implementation – the one described in the text or the one in the pseudocode? Thank you for your response.
![image](https://github.com/198808xc/Pangu-Weather/assets/100779955/7b57e61a-67b0-4b38-bcf7-c325d1a9fa3c)

**Comment by 198808xc** [comment]
Thanks for the correction. The description in the arXiv paper was a typo. Please follow the pseudocode.

**Comment by lizhuoq** [comment]
thanks
