### ISSUE TITLE
关于inference问题请教

### ISSUE THREAD

**Issue by weiyf2001** [198808xc/Pangu-Weather#68]
请问在使用大模型进行预测时，是使用较新数据多步预测效果更好还是使用步长对应数据一步预测效果好呢？比如，我要基于前一天(0~23)的历史数据预测第二天的数据，我要预测第二天1：00的数据，是基于前一天23：00时数据两步1H预测效果好呢还是直接使用前一天1：00数据基于24H的模型预测结果好呢？

**Comment by weiyf2001** [comment]
您在论文中预测使用的是贪心算法，但是当存在可用的时序历史数据进行24H内的短期预测时，如何权衡呢

**Comment by 198808xc** [comment]
你好，这是一个很好的问题。某些情况下，未必贪心算法能够得到最优预测，但并非你所说的这种情况。

如果我们需要根据t<=t0的气象变量，预测t0+2h时刻的气象变量，那么可以肯定地说，在t0时刻执行2次1h预测，可以得到最好的结果。如果选择在t0-22h时刻执行1次24h预测，虽然减少了迭代次数，但是24h模型的误差比1h模型大得多，不太可能会有更好的结果。如果感兴趣，可以尝试在t0-1h时刻执行1次3h预测，有可能会得到与t0时刻执行2次1h预测相当的结果。总的来说，模型需要在预报误差和迭代误差之间取得比较好的权衡。

假设需要根据t<=t0的气象变量，预测t0+23h的气象变量，那么情况就会很有意思。我们几乎可以肯定，这种情况下最优策略，并非在t0时刻执行贪心算法，即t0+6h+6h+6h+3h+1h+1h，而是在t0-1h时刻执行1次24h预测。在这种情况下，减少迭代误差带来的增益，超过了23h和24h预报误差的减益。

尽管如此，我们在文章中，还是简单地采用了贪心算法。在我们arXiv文章[https://arxiv.org/abs/2211.02556]的图8里，每隔一定的周期，预报精度会有一个小的波动，就是贪心算法非最优导致的。例如，每个整天的预报精度，一定会高于整天-1h的预报结果。

如果感兴趣，可以使用我们的预训练模型，继续探索这个课题。

**Comment by weiyf2001** [comment]
明白了，感谢~
